Update the runner to use current js(1)
linusg/libjs-test262 pull request #1
Opened 2021-05-25 22:59 UTC by nooga

2021-05-25 23:14 UTC, linusg requested changes

2021-05-25 23:14 UTC, linusg commented on main.py
> +                js, test262, test_file, timeout=args.timeout)
Please keep the file formatted with [black](https://github.com/psf/black) :)

2021-05-25 23:14 UTC, linusg commented on main.py
> +    except:
would be nice to capture the exception traceback as output for verbose mode. Something like this I suppose?

```suggestion
    except:
        output = traceback.format_exc()
```

(needs `import traceback` at the top, of course)

2021-05-25 23:15 UTC, linusg commented on main.py
> +                emoji = "❗️"
Oh and how about we swap the emojis with `NONZERO_EXIT_ERROR` here - explosion seems quite fitting for this :D

2021-05-25 23:24 UTC, nooga commented
👍 
I'll apply your suggestions in the morning.

2021-05-26 11:37 UTC, nooga commented
@linusg there you go :)

2021-05-26 11:54 UTC, linusg reviewed
I'd prefer to not squash these commits, could you please change the first one to not include the formatting change instead of fixing it in the second? Thanks!

2021-05-26 11:54 UTC, linusg commented on main.py
> +
```suggestion
```

no need for that :)

2021-05-26 12:51 UTC, nooga commented
> I'd prefer to not squash these commits, could you please change the first one to not include the formatting change instead of fixing it in the second? Thanks!

Erm... I just squashed the whitespace fix before reading this :D

2021-05-26 13:23 UTC, merged

2021-05-26 13:23 UTC, linusg commented
Awesome, thank you!!